const PUBLIC_BASE = import.meta.env.BASE_URL

export const LOCAL_ICON_PATHS = {
  'ph:bell-bold': `${PUBLIC_BASE}icons/ph-bell-bold.svg`,
  'ph:hard-drives-bold': `${PUBLIC_BASE}icons/ph-hard-drives-bold.svg`,
  'ph:globe-bold': `${PUBLIC_BASE}icons/ph-globe-bold.svg`,
  'ph:bell-ringing-bold': `${PUBLIC_BASE}icons/ph-bell-ringing-bold.svg`,
  'ph:download-simple-bold': `${PUBLIC_BASE}icons/ph-download-simple-bold.svg`,
  'ph:dots-six-vertical-bold': `${PUBLIC_BASE}icons/ph-dots-six-vertical-bold.svg`,
  'ph:caret-up-bold': `${PUBLIC_BASE}icons/ph-caret-up-bold.svg`,
  'ph:caret-down-bold': `${PUBLIC_BASE}icons/ph-caret-down-bold.svg`,
  'ph:arrows-clockwise-bold': `${PUBLIC_BASE}icons/ph-arrows-clockwise-bold.svg`,
  'ph:chat-circle-text-bold': `${PUBLIC_BASE}icons/ph-chat-circle-text-bold.svg`,
  'ph:chat-dots-bold': `${PUBLIC_BASE}icons/ph-chat-dots-bold.svg`,
  'ph:copy-bold': `${PUBLIC_BASE}icons/ph-copy-bold.svg`,
  'ph:file-text-bold': `${PUBLIC_BASE}icons/ph-file-text-bold.svg`,
  'ph:floppy-disk-bold': `${PUBLIC_BASE}icons/ph-floppy-disk-bold.svg`,
  'ph:magic-wand-bold': `${PUBLIC_BASE}icons/ph-magic-wand-bold.svg`,
  'ph:pause-circle-bold': `${PUBLIC_BASE}icons/ph-pause-circle-bold.svg`,
  'ph:play-circle-bold': `${PUBLIC_BASE}icons/ph-play-circle-bold.svg`,
  'ph:robot-bold': `${PUBLIC_BASE}icons/ph-robot-bold.svg`,
  'ph:x-circle-bold': `${PUBLIC_BASE}icons/ph-x-circle-bold.svg`,
  'ph:arrow-counter-clockwise-bold': `${PUBLIC_BASE}icons/ph-arrow-counter-clockwise-bold.svg`,
  'ph:arrow-left-bold': `${PUBLIC_BASE}icons/ph-arrow-left-bold.svg`,
  'ph:calendar-bold': `${PUBLIC_BASE}icons/ph-calendar-bold.svg`,
  'ph:chart-pie-slice-bold': `${PUBLIC_BASE}icons/ph-chart-pie-slice-bold.svg`,
  'ph:check-circle-bold': `${PUBLIC_BASE}icons/ph-check-circle-bold.svg`,
  'ph:clock-bold': `${PUBLIC_BASE}icons/ph-clock-bold.svg`,
  'ph:cloud-arrow-up-bold': `${PUBLIC_BASE}icons/ph-cloud-arrow-up-bold.svg`,
  'ph:coins-bold': `${PUBLIC_BASE}icons/ph-coins-bold.svg`,
  'ph:cooking-pot-bold': `${PUBLIC_BASE}icons/ph-cooking-pot-bold.svg`,
  'ph:gear-six-bold': `${PUBLIC_BASE}icons/ph-gear-six-bold.svg`,
  'ph:image-bold': `${PUBLIC_BASE}icons/ph-image-bold.svg`,
  'ph:list-checks-bold': `${PUBLIC_BASE}icons/ph-list-checks-bold.svg`,
  'ph:map-pin-bold': `${PUBLIC_BASE}icons/ph-map-pin-bold.svg`,
  'ph:package-bold': `${PUBLIC_BASE}icons/ph-package-bold.svg`,
  'ph:printer-bold': `${PUBLIC_BASE}icons/ph-printer-bold.svg`,
  'ph:pencil-simple-bold': `${PUBLIC_BASE}icons/ph-pencil-simple-bold.svg`,
  'ph:plus-bold': `${PUBLIC_BASE}icons/ph-plus-bold.svg`,
  'ph:plus-circle-bold': `${PUBLIC_BASE}icons/ph-plus-circle-bold.svg`,
  'ph:receipt-bold': `${PUBLIC_BASE}icons/ph-receipt-bold.svg`,
  'ph:shopping-cart-bold': `${PUBLIC_BASE}icons/ph-shopping-cart-bold.svg`,
  'ph:sign-out-bold': `${PUBLIC_BASE}icons/ph-sign-out-bold.svg`,
  'ph:storefront-bold': `${PUBLIC_BASE}icons/ph-storefront-bold.svg`,
  'ph:truck-bold': `${PUBLIC_BASE}icons/ph-truck-bold.svg`,
  'ph:users-bold': `${PUBLIC_BASE}icons/ph-users-bold.svg`,
  'ph:warning-circle-bold': `${PUBLIC_BASE}icons/ph-warning-circle-bold.svg`,
  'ph:x-bold': `${PUBLIC_BASE}icons/ph-x-bold.svg`,
  'ph:minus-bold': `${PUBLIC_BASE}icons/ph-minus-bold.svg`,
  'ph:calculator-bold': `${PUBLIC_BASE}icons/ph-calculator-bold.svg`,
  'ph:buildings-bold': `${PUBLIC_BASE}icons/ph-buildings-bold.svg`,
  'ph:scales-bold': `${PUBLIC_BASE}icons/ph-scales-bold.svg`,
  'ph:chart-bar-bold': `${PUBLIC_BASE}icons/ph-chart-bar-bold.svg`,
  'ph:trophy-bold': `${PUBLIC_BASE}icons/ph-trophy-bold.svg`,
  'ph:siren-bold': `${PUBLIC_BASE}icons/ph-siren-bold.svg`,
  'ph:note-pencil-bold': `${PUBLIC_BASE}icons/ph-note-pencil-bold.svg`,
  'ph:magnifying-glass-bold': `${PUBLIC_BASE}icons/ph-magnifying-glass-bold.svg`,
  'ph:clock-counter-clockwise-bold': `${PUBLIC_BASE}icons/ph-clock-counter-clockwise-bold.svg`,
  'ph:funnel-bold': `${PUBLIC_BASE}icons/ph-funnel-bold.svg`,
  'ph:info-bold': `${PUBLIC_BASE}icons/ph-info-bold.svg`,
  'ph:trash-bold': `${PUBLIC_BASE}icons/ph-trash-bold.svg`,
} as const

export type LocalIconName = keyof typeof LOCAL_ICON_PATHS
